site:
  name: "盆栽日記"
  page_title: ""
  page_description: "盆栽日記が提供する初心者のための、盆栽のホームページです。盆栽を作る手順や手入れの方法や、楽しみ方についても説明しています。"
  page_keywords: ["盆栽", "盆栽 作り方", "盆栽 初心者", "盆栽 手入れ"]
  meta_ogp_type: ""
  meta_ogp_image_path: ""